[package]
name = "lumina-part1-lum-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lum"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
tempfile = "3"
lumina-part1-parser = { path = "../02-parser" }
lumina-part1-typecheck = { path = "../03-typecheck" }
lumina-part1-codegen = { path = "../04-codegen" }
lumina-part1-runtime = { path = "../05-runtime-stdlib" }
lumina-part1-targets = { path = "../08-targets" }
